apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  namespace: default
  labels:
    component: svcs-acct-dply
spec:
  containers:
    - name: client
      image: muzij/counter
      ports:
        - containerPort: 3000


