apiVersion: v1
kind: Service
metadata:
  name: count
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31510
  selector:
    component: count

---
  
apiVersion: v1
kind: Pod
metadata:
  name: count
  namespace: default
  labels:
    component: count
spec:
  containers:
    - name: muzij/counter
      image: muzij/counter
      ports:
        - containerPort: 3000