apiVersion: v1
kind: Service
metadata:
  name: svcs-transaction-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31510
  selector:
    component: svcs-transaction-service

---
  
apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  namespace: default
  labels:
    component: svcs-transaction-service
spec:
  containers:
    - name: client
      image: muzij/counter
      ports:
        - containerPort: 3000