apiVersion: v1
kind: Service
metadata:
  name: counter-pod
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    component: counter-pod

---
  
apiVersion: v1
kind: Pod
metadata:
  name: count-pod
  namespace: default
  labels:
    component: counter-pod
spec:
  containers:
    - name: counter-pod
      image: muzij/counter
      ports:
        - containerPort: 3000